# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

include:
  - project: sysadmin/ci-utilities
    file:
      - /gitlab-templates/linux.yml
      - /gitlab-templates/freebsd.yml
      - /gitlab-templates/android.yml
      - /gitlab-templates/windows.yml
      - /gitlab-templates/flatpak.yml
      - /gitlab-templates/craft-android-apks.yml
  - project: sysadmin/ci-utilities
    ref: work/kloecker/enable-signing-for-windows-craft-job
    file:
      - /gitlab-templates/craft-windows-x86-64.yml
