# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

include:
  - project: sysadmin/ci-utilities
    ref: work/kloecker/craft-android
    file:
      - /gitlab-templates/craft-android-arm32.yml
      - /gitlab-templates/craft-android-arm64.yml
      - /gitlab-templates/craft-android-x86-64.yml
